server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    config:
      enabled: true

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      default-filters:
        - name: CircuitBreaker
          args:
            name: globalCB
            fallbackUri: forward:/fallback

  config:
    import: "optional:configserver:http://config-server:8888"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      globalCB:
        sliding-window-size: 10
        failure-rate-threshold: 50

  timelimiter:
    instances:
      globalCB:
        timeout-duration: 2s

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      enabled: true